import { MembershipType, MembershipStatus } from './member';

export type TransactionType = 'project' | 'operations' | 'dues' | 'merchandise';

export interface TransactionSplit {
  id: string;
  parentTransactionId: string;
  category: 'Projects & Activities' | 'Membership' | 'Administrative' | '';
  type: 'Income' | 'Expense';
  year?: number;
  projectId?: string | null;
  memberId?: string | null;
  purpose?: string | null;
  paymentRequestId?: string;
  amount: number;
  description: string;
  createdAt: string;
  createdBy: string;
  inventoryLinkId?: string;
  inventoryVariant?: string;
  inventoryQuantity?: number;
  projectTransactionId?: string | null;
  projectTransactionIds?: string[];
  autoGenerated?: boolean;
  status?: 'Reconciled' | 'Cleared' | 'Pending';
  reconciledAt?: string;
  reconciledBy?: string;
}

// Nested sub-objects for Transaction — fields that are never used as Firestore where() filters
// are grouped here for semantic clarity. Query fields (bankAccountId, status, memberId, etc.)
// stay flat at the Transaction root for index compatibility.

export interface TransactionReconciliation {
  reconciledAt?: string | null;
  reconciledBy?: string | null;
  matchedBankAmount?: number | null;
  matchedBankTxIds?: string[] | null;
  matchStatus?: 'unmatched' | 'partial' | 'full' | 'over' | null;
  /** Status held before matchTransactions() set it to Reconciled — restored on unmatch. */
  prevStatus?: 'Pending' | 'Cleared' | 'Reconciled' | 'Partially Reconciled' | 'Voided' | null;
}

export interface TransactionReversal {
  reversalOf?: string;
  reversalReason?: string;
  reversedBy?: string;
}

export interface TransactionOriginal {
  category?: string;
  projectId?: string | null;
  memberId?: string | null;
  paymentRequestId?: string | null;
  purpose?: string | null;
  year?: number;
}

export interface Transaction {
  id: string;
  date: string;
  description: string;
  purpose?: string | null;
  amount: number;
  type: 'Income' | 'Expense';
  category: 'Projects & Activities' | 'Membership' | 'Administrative' | ''; // '' used for split-parent records — see financeService.ts
  status: 'Pending' | 'Cleared' | 'Reconciled' | 'Partially Reconciled' | 'Voided';
  // Query fields — kept flat for Firestore composite index compatibility
  projectId?: string | null;
  memberId?: string | null;
  bankAccountId?: string;
  loId?: string | null;
  referenceNumber?: string | null;
  paymentRequestId?: string | null;
  projectTransactionId?: string | null;
  projectTransactionIds?: string[];
  transactionType?: TransactionType;
  splitIds?: string[];
  splits?: TransactionSplit[];
  isSplit?: boolean;
  year?: number;
  isSplitChild?: boolean;
  parentTransactionId?: string;
  inventoryLinkId?: string;
  inventoryVariant?: string;
  inventoryQuantity?: number;
  source?: 'bank_import' | 'manual';
  eventRegistrationId?: string;
  paymentMethod?: 'toyyib' | 'bank_transfer' | 'cash';
  toyyibBillCode?: string;
  createdAt?: string;
  updatedAt?: string;
  // Nested groups
  reconciliation?: TransactionReconciliation;
  reversal?: TransactionReversal;
  original?: TransactionOriginal;
}

export interface BankAccount {
  id: string;
  name: string;
  balance?: number;
  initialBalance?: number;
  currentBalance?: number; // SYNC-002: running balance maintained atomically by createTransaction/deleteTransaction
  currency: string;
  lastReconciled: string;
  lastReconciledAt?: string;
  lastReconciledBy?: string;
  accountNumber?: string;
  bankName?: string;
  accountType?: 'Current' | 'Savings' | 'Investment' | 'Fixed Deposit' | 'Cash' | 'Other';
  loId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface FinanceAlert {
  id: string;
  type: string;
  message: string;
  transactionId?: string;
  billCode?: string;
  eventRegistrationId?: string;
  paymentRequestId?: string;
  resolved: boolean;
  resolvedAt?: string;
  resolvedBy?: string;
  createdAt: string;
  updatedAt?: string;
}

export type PaymentRequestStatus = 'draft' | 'submitted' | 'approved' | 'rejected' | 'cancelled' | 'paid';

export interface PaymentRequestItem {
  purpose: string;
  amount: number;
  attachment?: string | null;
}

export interface PaymentRequest {
  id: string;
  applicantId: string;
  applicantName?: string | null;
  applicantEmail?: string | null;
  applicantPosition?: string | null;
  date: string;
  time: string;
  category: 'administrative' | 'projects_activities';
  activityId?: string | null;
  totalAmount: number;
  remark?: string | null;
  items: PaymentRequestItem[];
  claimFromBankAccountId?: string | null;
  bankName?: string | null;
  accountHolder?: string | null;
  accountNumber?: string | null;
  amount: number;
  purpose: string;
  activityRef?: string | null;
  referenceNumber: string;
  status: PaymentRequestStatus;
  attachmentUrls?: string[];
  combinedPdfFileId?: string;
  loId: string;
  createdAt: string;
  updatedAt: string;
  updatedBy?: string | null;
  reviewedBy?: string | null;
  reviewedAt?: string | null;
  rejectionReason?: string | null;
  paidAt?: string | null;
  expenseTxFailed?: boolean;
  amountSyncFailed?: boolean;
}

export interface ReconciliationRecord {
  id?: string;
  bankAccountId: string;
  reconciliationDate: string;
  statementBalance: number;
  systemBalance: number;
  adjustedBalance: number;
  discrepancies: ReconciliationDiscrepancy[];
  reconciledBy: string;
  notes?: string;
  status: 'in_progress' | 'completed';
  transactionTypeSummary: {
    project: number;
    operations: number;
    dues: number;
    merchandise: number;
  };
  createdAt?: string;
  updatedAt?: string;
}

export interface ReconciliationDiscrepancy {
  id: string;
  transactionId: string;
  type: 'missing' | 'amount_mismatch' | 'duplicate';
  expectedAmount?: number;
  actualAmount?: number;
  description: string;
  resolved?: boolean;
  resolutionNotes?: string;
}

