import { MembershipType, MembershipStatus } from './member';

export type TransactionType = 'project' | 'operations' | 'dues' | 'merchandise';

export interface TransactionSplit {
  id: string;
  parentTransactionId: string;
  category: 'Projects & Activities' | 'Membership' | 'Administrative' | '';
  type: 'Income' | 'Expense';
  year?: number;
  projectId?: string;
  memberId?: string;
  purpose?: string;
  paymentRequestId?: string;
  amount: number;
  description: string;
  createdAt: string;
  createdBy: string;
  inventoryLinkId?: string;
  inventoryVariant?: string;
  inventoryQuantity?: number;
  projectTransactionId?: string | null;
  projectTransactionIds?: string[];
  autoGenerated?: boolean;
}

export interface Transaction {
  id: string;
  date: string;
  description: string;
  purpose?: string;
  amount: number;
  type: 'Income' | 'Expense';
  category: 'Projects & Activities' | 'Membership' | 'Administrative';
  status: 'Pending' | 'Cleared' | 'Reconciled' | 'Partially Reconciled' | 'Voided';
  projectId?: string;
  memberId?: string;
  bankAccountId?: string;
  reconciledAt?: string;
  reconciledBy?: string;
  referenceNumber?: string | null;
  paymentRequestId?: string | null;
  projectTransactionId?: string | null;
  projectTransactionIds?: string[];
  transactionType?: TransactionType;
  splitIds?: string[];
  splits?: TransactionSplit[];
  isSplit?: boolean;
  year?: number;
  isSplitChild?: boolean;
  parentTransactionId?: string;
  inventoryLinkId?: string;
  inventoryVariant?: string;
  inventoryQuantity?: number;
  createdAt?: string;
  updatedAt?: string;
  originalCategory?: string;
  originalProjectId?: string;
  originalMemberId?: string;
  originalPaymentRequestId?: string;
  originalPurpose?: string;
  originalYear?: number;
  matchedBankAmount?: number;
  matchedBankTxIds?: string[];
  matchStatus?: 'unmatched' | 'partial' | 'full' | 'over';
  /** Status held immediately before matchTransactions() set it to Reconciled — lets unmatch restore it exactly. */
  prevStatus?: Transaction['status'] | null;
  source?: 'bank_import' | 'manual';
  eventRegistrationId?: string;
  paymentMethod?: 'toyyib' | 'bank_transfer' | 'cash';
  toyyibBillCode?: string;
}

export interface BankAccount {
  id: string;
  name: string;
  balance: number;
  initialBalance?: number;
  currency: string;
  lastReconciled: string;
  accountNumber?: string;
  bankName?: string;
  accountType?: 'Current' | 'Savings' | 'Investment' | 'Fixed Deposit' | 'Cash' | 'Other';
  loId?: string;
}

export interface FinanceAlert {
  id: string;
  type: string;
  message: string;
  transactionId?: string;
  billCode?: string;
  eventRegistrationId?: string;
  paymentRequestId?: string;
  resolved: boolean;
  resolvedAt?: string;
  resolvedBy?: string;
  createdAt: string;
}

export type PaymentRequestStatus = 'draft' | 'submitted' | 'approved' | 'rejected' | 'cancelled' | 'paid';

export interface PaymentRequestItem {
  purpose: string;
  amount: number;
  attachment?: string | null;
}

export interface PaymentRequest {
  id: string;
  applicantId: string;
  applicantName?: string | null;
  applicantEmail?: string | null;
  applicantPosition?: string | null;
  date: string;
  time: string;
  category: 'administrative' | 'projects_activities';
  activityId?: string | null;
  totalAmount: number;
  remark?: string | null;
  items: PaymentRequestItem[];
  claimFromBankAccountId?: string | null;
  bankName?: string | null;
  accountHolder?: string | null;
  accountNumber?: string | null;
  amount: number;
  purpose: string;
  activityRef?: string | null;
  referenceNumber: string;
  status: PaymentRequestStatus;
  attachmentUrls?: string[];
  loId: string;
  createdAt: string;
  updatedAt: string;
  updatedBy?: string | null;
  reviewedBy?: string | null;
  reviewedAt?: string | null;
  rejectionReason?: string | null;
  paidAt?: string | null;
  expenseTxFailed?: boolean;
  amountSyncFailed?: boolean;
}

export interface ReconciliationRecord {
  id?: string;
  bankAccountId: string;
  reconciliationDate: string;
  statementBalance: number;
  systemBalance: number;
  adjustedBalance: number;
  discrepancies: ReconciliationDiscrepancy[];
  reconciledBy: string;
  notes?: string;
  status: 'in_progress' | 'completed';
  transactionTypeSummary: {
    project: number;
    operations: number;
    dues: number;
    merchandise: number;
  };
  createdAt?: string;
  updatedAt?: string;
}

export interface ReconciliationDiscrepancy {
  id: string;
  transactionId: string;
  type: 'missing' | 'amount_mismatch' | 'duplicate';
  expectedAmount?: number;
  actualAmount?: number;
  description: string;
  resolved?: boolean;
  resolutionNotes?: string;
}

