/** All navigable view keys used by the main app shell. */
export type ViewType =
  | 'GUEST' | 'GUEST_EVENTS' | 'FLAGSHIP_PROJECTS' | 'GUEST_ABOUT'
  | 'GUEST_ENEWSLETTERS' | 'GUEST_DIRECTORY' | 'GUEST_PARTNERSHIPS'
  | 'DASHBOARD' | 'MEMBERS' | 'EVENTS' | 'PROJECTS'
  | 'FINANCE' | 'PAYMENT_REQUESTS' | 'GAMIFICATION' | 'INVENTORY'
  | 'DIRECTORY' | 'AUTOMATION' | 'KNOWLEDGE' | 'COMMUNICATION'
  | 'CLUBS' | 'SURVEYS' | 'BENEFITS' | 'DATA_IMPORT_EXPORT'
  | 'ADVERTISEMENTS' | 'AI_INSIGHTS' | 'TEMPLATES' | 'ACTIVITY_PLANS'
  | 'REPORTS' | 'DEVELOPER' | 'TOYYIB' | 'WHAPI_CONFIG' | 'API_CONFIG'
  | 'MEMBERSHIP_CONFIG' | 'ACCESS_CONFIG' | 'SYSTEM_CONFIG'
  | 'PUBLICATIONS' | 'RADAR_IMPORTER' | 'FLAGSHIP_PROJECTS_MGT'
  | 'SPONSORSHIPS' | 'ELECTIONS';
