import { ViewType } from '../../types/views';

export const VIEW_TITLES: Partial<Record<ViewType, string>> = {
  GUEST: 'Home',
  GUEST_EVENTS: 'Events',
  FLAGSHIP_PROJECTS: 'Flagship Projects',
  GUEST_ABOUT: 'About',
  GUEST_ENEWSLETTERS: 'E-Newsletters',
  GUEST_PARTNERSHIPS: 'Partnerships',
  DASHBOARD: 'Dashboard',
  MEMBERS: 'Members',
  EVENTS: 'Events',
  PROJECTS: 'Projects',
  FLAGSHIP_PROJECTS_MGT: 'Flagship Projects Mgt',
  FINANCE: 'Finance',
  PAYMENT_REQUESTS: 'Payment Requests',
  GAMIFICATION: 'Gamification',
  INVENTORY: 'Inventory',
  DIRECTORY: 'Business Directory',
  AUTOMATION: 'Automation Studio',
  KNOWLEDGE: 'Knowledge',
  COMMUNICATION: 'Communication',
  CLUBS: 'Hobby Clubs',
  ZOOM_BOOKING: 'Zoom Booking',
  SOCIAL_MEDIA: 'Social Media',
  SURVEYS: 'Surveys',
  BENEFITS: 'Member Benefits',
  DATA_IMPORT_EXPORT: 'Data Import/Export',
  RADAR_IMPORTER: 'Radar Data Importer',
  TOYYIB: 'ToyyibPay Test',
  ADVERTISEMENTS: 'Partnership & Promotions',
  AI_INSIGHTS: 'AI Insights',
  TEMPLATES: 'Templates',
  ACTIVITY_PLANS: 'Activity Plans',
  REPORTS: 'Reports',
  DEVELOPER: 'Developer Interface',
  WHAPI_CONFIG: 'Whapi Configuration',
  API_CONFIG: 'API Settings',
  MEMBERSHIP_CONFIG: 'Membership Config',
  ACCESS_CONFIG: 'Access Config',
  SYSTEM_CONFIG: 'System Config',
  PUBLICATIONS: 'Publications',
  SPONSORSHIPS: 'Sponsorships',
};

export const SHORT_VIEW_TITLES: Partial<Record<ViewType, string>> = {
  DASHBOARD: 'Dashboard',
  MEMBERS: 'Members',
  EVENTS: 'Event List',
  PROJECTS: 'Events Mgmt',
  FLAGSHIP_PROJECTS_MGT: 'Flagship',
  FINANCE: 'Finance',
  PAYMENT_REQUESTS: 'Payments',
  GAMIFICATION: 'Gamification',
  INVENTORY: 'Inventory',
  DIRECTORY: 'Biz Directory',
  AUTOMATION: 'Automation',
  KNOWLEDGE: 'Knowledge',
  COMMUNICATION: 'Communication',
  CLUBS: 'Hobby Clubs',
  ZOOM_BOOKING: 'Zoom',
  SOCIAL_MEDIA: 'Social Media',
  SURVEYS: 'Surveys',
  BENEFITS: 'Benefits',
  DATA_IMPORT_EXPORT: 'Data I/O',
  RADAR_IMPORTER: 'Radar Import',
  ADVERTISEMENTS: 'Partnerships',
  AI_INSIGHTS: 'AI Insights',
  TEMPLATES: 'Templates',
  ACTIVITY_PLANS: 'Activity Plans',
  REPORTS: 'Reports',
  DEVELOPER: 'Developer',
  TOYYIB: 'ToyyibPay',
  WHAPI_CONFIG: 'Whapi',
  API_CONFIG: 'API Settings',
  MEMBERSHIP_CONFIG: 'Membership',
  ACCESS_CONFIG: 'Access',
  SYSTEM_CONFIG: 'Config',
  PUBLICATIONS: 'Publications',
  SPONSORSHIPS: 'Sponsorships',
};

export const getViewTitle = (view: ViewType): string => VIEW_TITLES[view] ?? 'JCI LO Management';

export const getShortViewTitle = (view: ViewType): string => SHORT_VIEW_TITLES[view] ?? getViewTitle(view);
