// DEV MOCK: These Unsplash URLs will fail under CSP in production. Replace with Firebase Storage URLs or locally-bundled placeholders.
export const MOCK_SISTER_CHAPTER_MEMBERS = [
  {
    id: "scm1",
    name: "Kenji Tanaka",
    chineseName: "ç”°ä¸­ å¥äºŒ",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120",
    jciChapter: "JCI Nagoya",
    country: "Japan",
    companyName: "Tanaka Technologies Inc.",
    industry: "Technology",
    businessCategory: "Software Development",
    position: "CEO",
    email: "kenji.tanaka@jci-nagoya.org",
    phone: "+81 90-1234-5678",
    description: "Leading provider of industrial IoT solutions, automated production line software, and custom AI integrations for Japanese manufacturers.",
    collaborationNeeds: ["Distributors in Malaysia", "Smart factory partners"],
    specialOffer: "15% off initial system design and integration fees for JCI KL members."
  },
  {
    id: "scm2",
    name: "Maria Santos",
    chineseName: "Maria Santos",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120",
    jciChapter: "JCI Mandaue",
    country: "Philippines",
    companyName: "Santos Agri-Export Corp",
    industry: "Agriculture",
    businessCategory: "Food Processing & Export",
    position: "Managing Director",
    email: "maria.santos@jci-mandaue.org",
    phone: "+63 917-555-4321",
    description: "Premium tropical fruit processing and export. Specializing in organic dried mangoes, coconut flour, and freeze-dried exotic fruits.",
    collaborationNeeds: ["Southeast Asian importers", "Supermarket distributors"],
    specialOffer: "Free branding customization and sample kits for JCI member orders over $5,000."
  },
  {
    id: "scm3",
    name: "Christopher Chen",
    chineseName: "é™ˆå¿—è±ª",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=120",
    jciChapter: "JCI Orchid",
    country: "Singapore",
    companyName: "Orchid Wealth Advisory",
    industry: "Finance",
    businessCategory: "Wealth Management",
    position: "Senior Partner",
    email: "chris.chen@jci-orchid.org",
    phone: "+65 9876 5432",
    description: "Bespoke wealth management, offshore family office setup, and corporate cross-border tax planning strategies for regional businesses.",
    collaborationNeeds: ["Malaysian law firms", "SME founders expanding to SG"],
    specialOffer: "Complimentary 45-minute family office structuring consultation and tax health check."
  },
  {
    id: "scm4",
    name: "Irene Hsu",
    chineseName: "å¾å¥•é›¯",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=120",
    jciChapter: "JCI E-Metro",
    country: "Taiwan",
    companyName: "Green Horizon E-Commerce",
    industry: "E-Commerce",
    businessCategory: "Eco-Friendly Consumer Goods",
    position: "Founder",
    email: "irene.hsu@jci-emetro.org",
    phone: "+886 912 345 678",
    description: "E-commerce store and wholesale distributor of bio-degradable lifestyle goods, organic skincare, and zero-waste household items.",
    collaborationNeeds: ["Zero-waste retail distributors", "Malaysian packaging manufacturers"],
    specialOffer: "10% storewide discount and free shipping for bulk eco-packaging orders."
  },
  {
    id: "scm5",
    name: "David Lim",
    chineseName: "æž—è€€ç¥–",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=120",
    jciChapter: "JCI City",
    country: "Singapore",
    companyName: "Apex Creative Agency",
    industry: "Creative & Design",
    businessCategory: "Branding & UI/UX Design",
    position: "Creative Director",
    email: "david.lim@jci-city.org",
    phone: "+65 8123 4567",
    description: "Award-winning creative studio delivering high-end corporate re-branding, custom web interfaces, and digital advertising campaigns.",
    collaborationNeeds: ["IT development companies", "PR agencies in Malaysia"],
    specialOffer: "20% discount on first branding package or design project for JCI LOs and their members."
  }
];
