/**
 * Malaysia postcode → area/state lookup.
 * Lookup order: exact postcode match → prefix range → keyword scan → null.
 */

export interface AreaInfo {
  area: string;
  state: string;
}

// ---------------------------------------------------------------------------
// Exact postcode map — KL & Selangor (most relevant for JCI KL)
// ---------------------------------------------------------------------------
const EXACT: Record<string, AreaInfo> = {
  // Kuala Lumpur
  '50000': { area: 'Kuala Lumpur City Centre', state: 'Kuala Lumpur' },
  '50050': { area: 'Kuala Lumpur', state: 'Kuala Lumpur' },
  '50088': { area: 'Kuala Lumpur', state: 'Kuala Lumpur' },
  '50100': { area: 'Masjid India / Chow Kit', state: 'Kuala Lumpur' },
  '50150': { area: 'Chow Kit', state: 'Kuala Lumpur' },
  '50200': { area: 'Brickfields', state: 'Kuala Lumpur' },
  '50300': { area: 'Pudu', state: 'Kuala Lumpur' },
  '50350': { area: 'Pudu', state: 'Kuala Lumpur' },
  '50400': { area: 'Jalan Imbi / Bukit Bintang', state: 'Kuala Lumpur' },
  '50450': { area: 'Bukit Bintang', state: 'Kuala Lumpur' },
  '50460': { area: 'Chow Kit', state: 'Kuala Lumpur' },
  '50470': { area: 'Chow Kit', state: 'Kuala Lumpur' },
  '50480': { area: 'Jalan Tuanku Abdul Halim', state: 'Kuala Lumpur' },
  '50490': { area: 'Jalan Tuanku Abdul Halim', state: 'Kuala Lumpur' },
  '50500': { area: 'Jalan Parlimen', state: 'Kuala Lumpur' },
  '50550': { area: 'Jalan Parlimen', state: 'Kuala Lumpur' },
  '50600': { area: 'Jalan Sultan Ismail', state: 'Kuala Lumpur' },
  '50620': { area: 'Jalan P Ramlee', state: 'Kuala Lumpur' },
  '50630': { area: 'Jalan P Ramlee', state: 'Kuala Lumpur' },
  '50700': { area: 'Jalan Raja Laut', state: 'Kuala Lumpur' },
  '50720': { area: 'Jalan Raja Laut', state: 'Kuala Lumpur' },
  '50740': { area: 'Jalan Raja Laut', state: 'Kuala Lumpur' },
  '50760': { area: 'Jalan Raja Laut', state: 'Kuala Lumpur' },
  '50770': { area: 'Jalan Raja Laut', state: 'Kuala Lumpur' },
  '50800': { area: 'Sentul', state: 'Kuala Lumpur' },
  '50900': { area: 'Sentul', state: 'Kuala Lumpur' },
  '51000': { area: 'Sentul', state: 'Kuala Lumpur' },
  '51100': { area: 'Sentul', state: 'Kuala Lumpur' },
  '51200': { area: 'Sentul', state: 'Kuala Lumpur' },
  '51300': { area: 'Sentul', state: 'Kuala Lumpur' },
  '51400': { area: 'Sentul', state: 'Kuala Lumpur' },
  '51500': { area: 'Kepong', state: 'Kuala Lumpur' },
  '51700': { area: 'Kepong', state: 'Kuala Lumpur' },
  '51800': { area: 'Kepong', state: 'Kuala Lumpur' },
  '51900': { area: 'Kepong', state: 'Kuala Lumpur' },
  '52000': { area: 'Kepong', state: 'Kuala Lumpur' },
  '52100': { area: 'Kepong', state: 'Kuala Lumpur' },
  '52200': { area: 'Kepong', state: 'Kuala Lumpur' },
  '53000': { area: 'Setapak', state: 'Kuala Lumpur' },
  '53100': { area: 'Setapak', state: 'Kuala Lumpur' },
  '53200': { area: 'Setapak', state: 'Kuala Lumpur' },
  '53300': { area: 'Setapak', state: 'Kuala Lumpur' },
  '54000': { area: 'Jalan Ipoh', state: 'Kuala Lumpur' },
  '54100': { area: 'Jalan Ipoh', state: 'Kuala Lumpur' },
  '54200': { area: 'Jalan Ipoh', state: 'Kuala Lumpur' },
  '55000': { area: 'Cheras', state: 'Kuala Lumpur' },
  '55100': { area: 'Cheras', state: 'Kuala Lumpur' },
  '55200': { area: 'Cheras', state: 'Kuala Lumpur' },
  '56000': { area: 'Cheras', state: 'Kuala Lumpur' },
  '56100': { area: 'Cheras', state: 'Kuala Lumpur' },
  '57000': { area: 'Cheras', state: 'Kuala Lumpur' },
  '57100': { area: 'Salak South', state: 'Kuala Lumpur' },
  '58000': { area: 'Kuala Lumpur Selatan', state: 'Kuala Lumpur' },
  '58100': { area: 'Kuala Lumpur Selatan', state: 'Kuala Lumpur' },
  '58200': { area: 'Bukit Jalil', state: 'Kuala Lumpur' },
  '59000': { area: 'Bangsar', state: 'Kuala Lumpur' },
  '59100': { area: 'Bangsar', state: 'Kuala Lumpur' },
  '59200': { area: 'Bangsar', state: 'Kuala Lumpur' },
  '60000': { area: 'Sri Petaling', state: 'Kuala Lumpur' },

  // Putrajaya
  '62000': { area: 'Putrajaya', state: 'Putrajaya' },
  '62100': { area: 'Putrajaya', state: 'Putrajaya' },
  '62200': { area: 'Putrajaya', state: 'Putrajaya' },
  '62300': { area: 'Putrajaya', state: 'Putrajaya' },
  '62400': { area: 'Putrajaya', state: 'Putrajaya' },
  '62500': { area: 'Putrajaya', state: 'Putrajaya' },
  '62502': { area: 'Putrajaya', state: 'Putrajaya' },
  '62504': { area: 'Putrajaya', state: 'Putrajaya' },
  '62506': { area: 'Putrajaya', state: 'Putrajaya' },
  '62510': { area: 'Putrajaya', state: 'Putrajaya' },
  '62512': { area: 'Putrajaya', state: 'Putrajaya' },
  '62514': { area: 'Putrajaya', state: 'Putrajaya' },
  '62516': { area: 'Putrajaya', state: 'Putrajaya' },
  '62518': { area: 'Putrajaya', state: 'Putrajaya' },
  '62520': { area: 'Putrajaya', state: 'Putrajaya' },
  '62522': { area: 'Putrajaya', state: 'Putrajaya' },
  '62524': { area: 'Putrajaya', state: 'Putrajaya' },
  '62526': { area: 'Putrajaya', state: 'Putrajaya' },
  '62528': { area: 'Putrajaya', state: 'Putrajaya' },
  '62530': { area: 'Putrajaya', state: 'Putrajaya' },
  '62600': { area: 'Putrajaya', state: 'Putrajaya' },
  '62604': { area: 'Putrajaya', state: 'Putrajaya' },
  '62606': { area: 'Putrajaya', state: 'Putrajaya' },
  '62608': { area: 'Putrajaya', state: 'Putrajaya' },
  '62610': { area: 'Putrajaya', state: 'Putrajaya' },
  '62612': { area: 'Putrajaya', state: 'Putrajaya' },
  '62614': { area: 'Putrajaya', state: 'Putrajaya' },
  '62616': { area: 'Putrajaya', state: 'Putrajaya' },
  '62618': { area: 'Putrajaya', state: 'Putrajaya' },
  '62620': { area: 'Putrajaya', state: 'Putrajaya' },
  '62622': { area: 'Putrajaya', state: 'Putrajaya' },
  '62624': { area: 'Putrajaya', state: 'Putrajaya' },
  '62626': { area: 'Putrajaya', state: 'Putrajaya' },
  '62628': { area: 'Putrajaya', state: 'Putrajaya' },
  '62630': { area: 'Putrajaya', state: 'Putrajaya' },
  '62632': { area: 'Putrajaya', state: 'Putrajaya' },
  '62634': { area: 'Putrajaya', state: 'Putrajaya' },
  '62636': { area: 'Putrajaya', state: 'Putrajaya' },
  '62638': { area: 'Putrajaya', state: 'Putrajaya' },
  '62640': { area: 'Putrajaya', state: 'Putrajaya' },
  '62642': { area: 'Putrajaya', state: 'Putrajaya' },
  '62644': { area: 'Putrajaya', state: 'Putrajaya' },
  '62646': { area: 'Putrajaya', state: 'Putrajaya' },
  '62648': { area: 'Putrajaya', state: 'Putrajaya' },
  '62650': { area: 'Putrajaya', state: 'Putrajaya' },
  '62652': { area: 'Putrajaya', state: 'Putrajaya' },
  '62654': { area: 'Putrajaya', state: 'Putrajaya' },
  '62656': { area: 'Putrajaya', state: 'Putrajaya' },
  '62658': { area: 'Putrajaya', state: 'Putrajaya' },
  '62660': { area: 'Putrajaya', state: 'Putrajaya' },
  '62662': { area: 'Putrajaya', state: 'Putrajaya' },

  // Selangor — Petaling
  '40000': { area: 'Shah Alam', state: 'Selangor' },
  '40100': { area: 'Shah Alam', state: 'Selangor' },
  '40150': { area: 'Shah Alam', state: 'Selangor' },
  '40160': { area: 'Shah Alam', state: 'Selangor' },
  '40170': { area: 'Shah Alam', state: 'Selangor' },
  '40200': { area: 'Shah Alam', state: 'Selangor' },
  '40250': { area: 'Shah Alam', state: 'Selangor' },
  '40300': { area: 'Shah Alam', state: 'Selangor' },
  '40350': { area: 'Shah Alam', state: 'Selangor' },
  '40400': { area: 'Shah Alam', state: 'Selangor' },
  '40450': { area: 'Shah Alam', state: 'Selangor' },
  '40460': { area: 'Shah Alam', state: 'Selangor' },
  '40470': { area: 'Shah Alam', state: 'Selangor' },
  '40480': { area: 'Shah Alam', state: 'Selangor' },
  '40490': { area: 'Shah Alam', state: 'Selangor' },
  '40500': { area: 'Shah Alam', state: 'Selangor' },
  '40502': { area: 'Shah Alam', state: 'Selangor' },
  '40504': { area: 'Shah Alam', state: 'Selangor' },
  '40506': { area: 'Shah Alam', state: 'Selangor' },
  '40508': { area: 'Shah Alam', state: 'Selangor' },
  '40510': { area: 'Shah Alam', state: 'Selangor' },
  '40512': { area: 'Shah Alam', state: 'Selangor' },
  '40514': { area: 'Shah Alam', state: 'Selangor' },
  '40516': { area: 'Shah Alam', state: 'Selangor' },
  '40518': { area: 'Shah Alam', state: 'Selangor' },
  '40520': { area: 'Shah Alam', state: 'Selangor' },
  '40522': { area: 'Shah Alam', state: 'Selangor' },
  '40524': { area: 'Shah Alam', state: 'Selangor' },
  '40526': { area: 'Shah Alam', state: 'Selangor' },
  '40528': { area: 'Shah Alam', state: 'Selangor' },
  '40530': { area: 'Shah Alam', state: 'Selangor' },
  '40532': { area: 'Shah Alam', state: 'Selangor' },
  '40534': { area: 'Shah Alam', state: 'Selangor' },
  '40536': { area: 'Shah Alam', state: 'Selangor' },
  '40538': { area: 'Shah Alam', state: 'Selangor' },
  '40540': { area: 'Shah Alam', state: 'Selangor' },
  '40542': { area: 'Shah Alam', state: 'Selangor' },
  '40544': { area: 'Shah Alam', state: 'Selangor' },
  '40546': { area: 'Shah Alam', state: 'Selangor' },
  '40548': { area: 'Shah Alam', state: 'Selangor' },
  '40550': { area: 'Shah Alam', state: 'Selangor' },
  '40552': { area: 'Shah Alam', state: 'Selangor' },
  '40554': { area: 'Shah Alam', state: 'Selangor' },
  '40556': { area: 'Shah Alam', state: 'Selangor' },
  '40558': { area: 'Shah Alam', state: 'Selangor' },
  '40560': { area: 'Shah Alam', state: 'Selangor' },
  '40562': { area: 'Shah Alam', state: 'Selangor' },
  '40564': { area: 'Shah Alam', state: 'Selangor' },
  '40566': { area: 'Shah Alam', state: 'Selangor' },
  '40568': { area: 'Shah Alam', state: 'Selangor' },
  '40570': { area: 'Shah Alam', state: 'Selangor' },
  '40572': { area: 'Shah Alam', state: 'Selangor' },
  '40574': { area: 'Shah Alam', state: 'Selangor' },
  '40576': { area: 'Shah Alam', state: 'Selangor' },
  '40578': { area: 'Shah Alam', state: 'Selangor' },
  '40580': { area: 'Shah Alam', state: 'Selangor' },
  '40582': { area: 'Shah Alam', state: 'Selangor' },
  '40584': { area: 'Shah Alam', state: 'Selangor' },
  '40586': { area: 'Shah Alam', state: 'Selangor' },
  '40588': { area: 'Shah Alam', state: 'Selangor' },
  '40590': { area: 'Shah Alam', state: 'Selangor' },
  '40592': { area: 'Shah Alam', state: 'Selangor' },
  '40594': { area: 'Shah Alam', state: 'Selangor' },
  '40596': { area: 'Shah Alam', state: 'Selangor' },
  '40598': { area: 'Shah Alam', state: 'Selangor' },
  '40600': { area: 'Shah Alam', state: 'Selangor' },
  '40604': { area: 'Shah Alam', state: 'Selangor' },
  '40606': { area: 'Shah Alam', state: 'Selangor' },
  '40608': { area: 'Shah Alam', state: 'Selangor' },
  '40610': { area: 'Shah Alam', state: 'Selangor' },
  '40612': { area: 'Shah Alam', state: 'Selangor' },
  '40614': { area: 'Shah Alam', state: 'Selangor' },
  '40616': { area: 'Shah Alam', state: 'Selangor' },
  '40618': { area: 'Shah Alam', state: 'Selangor' },
  '40620': { area: 'Shah Alam', state: 'Selangor' },
  '40622': { area: 'Shah Alam', state: 'Selangor' },
  '40624': { area: 'Shah Alam', state: 'Selangor' },
  '40626': { area: 'Shah Alam', state: 'Selangor' },
  '40628': { area: 'Shah Alam', state: 'Selangor' },
  '40630': { area: 'Shah Alam', state: 'Selangor' },
  '40632': { area: 'Shah Alam', state: 'Selangor' },
  '40634': { area: 'Shah Alam', state: 'Selangor' },
  '40636': { area: 'Shah Alam', state: 'Selangor' },
  '40638': { area: 'Shah Alam', state: 'Selangor' },
  '40640': { area: 'Shah Alam', state: 'Selangor' },
  '40642': { area: 'Shah Alam', state: 'Selangor' },
  '40644': { area: 'Shah Alam', state: 'Selangor' },
  '40646': { area: 'Shah Alam', state: 'Selangor' },
  '40648': { area: 'Shah Alam', state: 'Selangor' },
  '40650': { area: 'Shah Alam', state: 'Selangor' },
  '40652': { area: 'Shah Alam', state: 'Selangor' },
  '40654': { area: 'Shah Alam', state: 'Selangor' },
  '40656': { area: 'Shah Alam', state: 'Selangor' },
  '40658': { area: 'Shah Alam', state: 'Selangor' },
  '40660': { area: 'Shah Alam', state: 'Selangor' },
  '40662': { area: 'Shah Alam', state: 'Selangor' },
  '40664': { area: 'Shah Alam', state: 'Selangor' },
  '40666': { area: 'Shah Alam', state: 'Selangor' },
  '40668': { area: 'Shah Alam', state: 'Selangor' },
  '40670': { area: 'Shah Alam', state: 'Selangor' },
  '40672': { area: 'Shah Alam', state: 'Selangor' },
  '40674': { area: 'Shah Alam', state: 'Selangor' },
  '40676': { area: 'Shah Alam', state: 'Selangor' },
  '40678': { area: 'Shah Alam', state: 'Selangor' },
  '40680': { area: 'Shah Alam', state: 'Selangor' },
  '40682': { area: 'Shah Alam', state: 'Selangor' },
  '40684': { area: 'Shah Alam', state: 'Selangor' },
  '40686': { area: 'Shah Alam', state: 'Selangor' },
  '40688': { area: 'Shah Alam', state: 'Selangor' },
  '40690': { area: 'Shah Alam', state: 'Selangor' },
  '40692': { area: 'Shah Alam', state: 'Selangor' },
  '40694': { area: 'Shah Alam', state: 'Selangor' },
  '40696': { area: 'Shah Alam', state: 'Selangor' },
  '40698': { area: 'Shah Alam', state: 'Selangor' },
  '40700': { area: 'Shah Alam', state: 'Selangor' },
  '40702': { area: 'Shah Alam', state: 'Selangor' },
  '40704': { area: 'Shah Alam', state: 'Selangor' },
  '40706': { area: 'Shah Alam', state: 'Selangor' },
  '40708': { area: 'Shah Alam', state: 'Selangor' },
  '40710': { area: 'Shah Alam', state: 'Selangor' },
  '40712': { area: 'Shah Alam', state: 'Selangor' },
  '40714': { area: 'Shah Alam', state: 'Selangor' },
  '40716': { area: 'Shah Alam', state: 'Selangor' },
  '40718': { area: 'Shah Alam', state: 'Selangor' },
  '40720': { area: 'Shah Alam', state: 'Selangor' },
  '40722': { area: 'Shah Alam', state: 'Selangor' },
  '40724': { area: 'Shah Alam', state: 'Selangor' },
  '40726': { area: 'Shah Alam', state: 'Selangor' },
  '40728': { area: 'Shah Alam', state: 'Selangor' },
  '40730': { area: 'Shah Alam', state: 'Selangor' },
  '40732': { area: 'Shah Alam', state: 'Selangor' },
  '40734': { area: 'Shah Alam', state: 'Selangor' },
  '40736': { area: 'Shah Alam', state: 'Selangor' },
  '40738': { area: 'Shah Alam', state: 'Selangor' },
  '40740': { area: 'Shah Alam', state: 'Selangor' },
  '40742': { area: 'Shah Alam', state: 'Selangor' },
  '40744': { area: 'Shah Alam', state: 'Selangor' },
  '40746': { area: 'Shah Alam', state: 'Selangor' },
  '40748': { area: 'Shah Alam', state: 'Selangor' },
  '40750': { area: 'Shah Alam', state: 'Selangor' },
  '40752': { area: 'Shah Alam', state: 'Selangor' },
  '40754': { area: 'Shah Alam', state: 'Selangor' },
  '40756': { area: 'Shah Alam', state: 'Selangor' },
  '40758': { area: 'Shah Alam', state: 'Selangor' },
  '40760': { area: 'Shah Alam', state: 'Selangor' },
  '40762': { area: 'Shah Alam', state: 'Selangor' },
  '40764': { area: 'Shah Alam', state: 'Selangor' },
  '40766': { area: 'Shah Alam', state: 'Selangor' },
  '40768': { area: 'Shah Alam', state: 'Selangor' },
  '40770': { area: 'Shah Alam', state: 'Selangor' },
  '40772': { area: 'Shah Alam', state: 'Selangor' },
  '40774': { area: 'Shah Alam', state: 'Selangor' },
  '40776': { area: 'Shah Alam', state: 'Selangor' },
  '40778': { area: 'Shah Alam', state: 'Selangor' },
  '40780': { area: 'Shah Alam', state: 'Selangor' },
  '40782': { area: 'Shah Alam', state: 'Selangor' },
  '40784': { area: 'Shah Alam', state: 'Selangor' },
  '40786': { area: 'Shah Alam', state: 'Selangor' },
  '40788': { area: 'Shah Alam', state: 'Selangor' },
  '40790': { area: 'Shah Alam', state: 'Selangor' },
  '40792': { area: 'Shah Alam', state: 'Selangor' },
  '40794': { area: 'Shah Alam', state: 'Selangor' },
  '40796': { area: 'Shah Alam', state: 'Selangor' },
  '40798': { area: 'Shah Alam', state: 'Selangor' },
  '40800': { area: 'Shah Alam', state: 'Selangor' },
  '40990': { area: 'Shah Alam', state: 'Selangor' },
  '41000': { area: 'Klang', state: 'Selangor' },
  '41050': { area: 'Klang', state: 'Selangor' },
  '41100': { area: 'Klang', state: 'Selangor' },
  '41150': { area: 'Klang', state: 'Selangor' },
  '41200': { area: 'Klang', state: 'Selangor' },
  '41250': { area: 'Klang', state: 'Selangor' },
  '41300': { area: 'Klang', state: 'Selangor' },
  '41400': { area: 'Klang', state: 'Selangor' },
  '41450': { area: 'Klang', state: 'Selangor' },
  '41500': { area: 'Klang', state: 'Selangor' },
  '41560': { area: 'Klang', state: 'Selangor' },
  '41600': { area: 'Klang', state: 'Selangor' },
  '41700': { area: 'Klang', state: 'Selangor' },
  '42000': { area: 'Pelabuhan Klang', state: 'Selangor' },
  '42100': { area: 'Pelabuhan Klang', state: 'Selangor' },
  '42200': { area: 'Kapar', state: 'Selangor' },
  '42300': { area: 'Banting', state: 'Selangor' },
  '42400': { area: 'Telok Panglima Garang', state: 'Selangor' },
  '42450': { area: 'Telok Panglima Garang', state: 'Selangor' },
  '42500': { area: 'Carey Island', state: 'Selangor' },
  '42600': { area: 'Jenjarom', state: 'Selangor' },
  '42700': { area: 'Banting', state: 'Selangor' },
  '42800': { area: 'Banting', state: 'Selangor' },
  '42900': { area: 'Banting', state: 'Selangor' },
  '43000': { area: 'Kajang', state: 'Selangor' },
  '43100': { area: 'Hulu Langat', state: 'Selangor' },
  '43200': { area: 'Cheras (Selangor)', state: 'Selangor' },
  '43300': { area: 'Balakong', state: 'Selangor' },
  '43400': { area: 'Serdang', state: 'Selangor' },
  '43500': { area: 'Semenyih', state: 'Selangor' },
  '43600': { area: 'Kajang', state: 'Selangor' },
  '43650': { area: 'Bandar Baru Bangi', state: 'Selangor' },
  '43700': { area: 'Beranang', state: 'Selangor' },
  '43800': { area: 'Dengkil', state: 'Selangor' },
  '43900': { area: 'Sepang', state: 'Selangor' },
  '44000': { area: 'Kuala Kubu Baru', state: 'Selangor' },
  '44100': { area: 'Batang Kali', state: 'Selangor' },
  '44200': { area: 'Kerling', state: 'Selangor' },
  '44300': { area: 'Ulu Yam', state: 'Selangor' },
  '44400': { area: 'Bestari Jaya', state: 'Selangor' },
  '44500': { area: 'Sabak Bernam', state: 'Selangor' },
  '44600': { area: 'Sungai Besar', state: 'Selangor' },
  '44700': { area: 'Sekinchan', state: 'Selangor' },
  '44800': { area: 'Kuala Selangor', state: 'Selangor' },
  '44900': { area: 'Tanjong Karang', state: 'Selangor' },
  '45000': { area: 'Kuala Selangor', state: 'Selangor' },
  '45100': { area: 'Kuala Selangor', state: 'Selangor' },
  '45200': { area: 'Kuala Selangor', state: 'Selangor' },
  '45300': { area: 'Kuala Selangor', state: 'Selangor' },
  '45400': { area: 'Tanjong Karang', state: 'Selangor' },
  '45500': { area: 'Tanjong Karang', state: 'Selangor' },
  '45600': { area: 'Sabak Bernam', state: 'Selangor' },
  '45700': { area: 'Sabak Bernam', state: 'Selangor' },
  '45800': { area: 'Sabak Bernam', state: 'Selangor' },
  '45900': { area: 'Sabak Bernam', state: 'Selangor' },
  '46000': { area: 'Petaling Jaya', state: 'Selangor' },
  '46050': { area: 'Petaling Jaya', state: 'Selangor' },
  '46100': { area: 'Petaling Jaya', state: 'Selangor' },
  '46150': { area: 'Petaling Jaya', state: 'Selangor' },
  '46200': { area: 'Petaling Jaya', state: 'Selangor' },
  '46300': { area: 'Petaling Jaya', state: 'Selangor' },
  '46350': { area: 'Petaling Jaya', state: 'Selangor' },
  '46400': { area: 'Petaling Jaya', state: 'Selangor' },
  '46450': { area: 'Petaling Jaya', state: 'Selangor' },
  '46500': { area: 'Petaling Jaya', state: 'Selangor' },
  '46506': { area: 'Petaling Jaya', state: 'Selangor' },
  '46508': { area: 'Petaling Jaya', state: 'Selangor' },
  '46510': { area: 'Petaling Jaya', state: 'Selangor' },
  '46512': { area: 'Petaling Jaya', state: 'Selangor' },
  '46514': { area: 'Petaling Jaya', state: 'Selangor' },
  '46516': { area: 'Petaling Jaya', state: 'Selangor' },
  '46518': { area: 'Petaling Jaya', state: 'Selangor' },
  '46520': { area: 'Petaling Jaya', state: 'Selangor' },
  '46522': { area: 'Petaling Jaya', state: 'Selangor' },
  '46524': { area: 'Petaling Jaya', state: 'Selangor' },
  '46526': { area: 'Petaling Jaya', state: 'Selangor' },
  '46528': { area: 'Petaling Jaya', state: 'Selangor' },
  '46530': { area: 'Petaling Jaya', state: 'Selangor' },
  '46532': { area: 'Petaling Jaya', state: 'Selangor' },
  '46534': { area: 'Petaling Jaya', state: 'Selangor' },
  '46536': { area: 'Petaling Jaya', state: 'Selangor' },
  '46538': { area: 'Petaling Jaya', state: 'Selangor' },
  '46540': { area: 'Petaling Jaya', state: 'Selangor' },
  '46542': { area: 'Petaling Jaya', state: 'Selangor' },
  '46544': { area: 'Petaling Jaya', state: 'Selangor' },
  '46546': { area: 'Petaling Jaya', state: 'Selangor' },
  '46548': { area: 'Petaling Jaya', state: 'Selangor' },
  '46550': { area: 'Petaling Jaya', state: 'Selangor' },
  '46560': { area: 'Petaling Jaya', state: 'Selangor' },
  '46570': { area: 'Petaling Jaya', state: 'Selangor' },
  '46580': { area: 'Petaling Jaya', state: 'Selangor' },
  '46590': { area: 'Petaling Jaya', state: 'Selangor' },
  '46600': { area: 'Petaling Jaya', state: 'Selangor' },
  '46610': { area: 'Petaling Jaya', state: 'Selangor' },
  '46620': { area: 'Petaling Jaya', state: 'Selangor' },
  '46630': { area: 'Petaling Jaya', state: 'Selangor' },
  '46640': { area: 'Petaling Jaya', state: 'Selangor' },
  '46650': { area: 'Petaling Jaya', state: 'Selangor' },
  '46660': { area: 'Petaling Jaya', state: 'Selangor' },
  '46670': { area: 'Petaling Jaya', state: 'Selangor' },
  '46680': { area: 'Petaling Jaya', state: 'Selangor' },
  '46690': { area: 'Petaling Jaya', state: 'Selangor' },
  '46700': { area: 'Petaling Jaya', state: 'Selangor' },
  '46710': { area: 'Petaling Jaya', state: 'Selangor' },
  '46720': { area: 'Petaling Jaya', state: 'Selangor' },
  '46730': { area: 'Petaling Jaya', state: 'Selangor' },
  '46740': { area: 'Petaling Jaya', state: 'Selangor' },
  '46750': { area: 'Petaling Jaya', state: 'Selangor' },
  '46760': { area: 'Petaling Jaya', state: 'Selangor' },
  '46770': { area: 'Petaling Jaya', state: 'Selangor' },
  '46780': { area: 'Petaling Jaya', state: 'Selangor' },
  '46790': { area: 'Petaling Jaya', state: 'Selangor' },
  '46800': { area: 'Petaling Jaya', state: 'Selangor' },
  '46810': { area: 'Petaling Jaya', state: 'Selangor' },
  '46820': { area: 'Petaling Jaya', state: 'Selangor' },
  '46830': { area: 'Petaling Jaya', state: 'Selangor' },
  '46840': { area: 'Petaling Jaya', state: 'Selangor' },
  '46850': { area: 'Petaling Jaya', state: 'Selangor' },
  '46860': { area: 'Petaling Jaya', state: 'Selangor' },
  '46870': { area: 'Petaling Jaya', state: 'Selangor' },
  '46880': { area: 'Petaling Jaya', state: 'Selangor' },
  '46890': { area: 'Petaling Jaya', state: 'Selangor' },
  '46900': { area: 'Petaling Jaya', state: 'Selangor' },
  '46910': { area: 'Petaling Jaya', state: 'Selangor' },
  '46920': { area: 'Petaling Jaya', state: 'Selangor' },
  '46930': { area: 'Petaling Jaya', state: 'Selangor' },
  '46940': { area: 'Petaling Jaya', state: 'Selangor' },
  '46950': { area: 'Petaling Jaya', state: 'Selangor' },
  '46960': { area: 'Petaling Jaya', state: 'Selangor' },
  '46970': { area: 'Petaling Jaya', state: 'Selangor' },
  '46980': { area: 'Petaling Jaya', state: 'Selangor' },
  '46990': { area: 'Petaling Jaya', state: 'Selangor' },
  '47000': { area: 'Subang Jaya', state: 'Selangor' },
  '47100': { area: 'Subang Jaya', state: 'Selangor' },
  '47200': { area: 'Subang Jaya', state: 'Selangor' },
  '47300': { area: 'Subang Jaya', state: 'Selangor' },
  '47400': { area: 'Subang Jaya', state: 'Selangor' },
  '47500': { area: 'Subang Jaya', state: 'Selangor' },
  '47600': { area: 'Subang Jaya', state: 'Selangor' },
  '47620': { area: 'Subang Jaya', state: 'Selangor' },
  '47630': { area: 'Subang Jaya', state: 'Selangor' },
  '47640': { area: 'Subang Jaya', state: 'Selangor' },
  '47650': { area: 'Subang Jaya', state: 'Selangor' },
  '47700': { area: 'Petaling Jaya', state: 'Selangor' },
  '47800': { area: 'Petaling Jaya', state: 'Selangor' },
  '47810': { area: 'Petaling Jaya', state: 'Selangor' },
  '47820': { area: 'Petaling Jaya', state: 'Selangor' },
  '47830': { area: 'Petaling Jaya', state: 'Selangor' },
  '47840': { area: 'Petaling Jaya', state: 'Selangor' },
  '47850': { area: 'Petaling Jaya', state: 'Selangor' },
  '47860': { area: 'Petaling Jaya', state: 'Selangor' },
  '47870': { area: 'Petaling Jaya', state: 'Selangor' },
  '47880': { area: 'Petaling Jaya', state: 'Selangor' },
  '47890': { area: 'Petaling Jaya', state: 'Selangor' },
  '47900': { area: 'Petaling Jaya', state: 'Selangor' },
  '47910': { area: 'Petaling Jaya', state: 'Selangor' },
  '47920': { area: 'Petaling Jaya', state: 'Selangor' },
  '47930': { area: 'Petaling Jaya', state: 'Selangor' },
  '47940': { area: 'Petaling Jaya', state: 'Selangor' },
  '47950': { area: 'Petaling Jaya', state: 'Selangor' },
  '47960': { area: 'Petaling Jaya', state: 'Selangor' },
  '47970': { area: 'Petaling Jaya', state: 'Selangor' },
  '47980': { area: 'Petaling Jaya', state: 'Selangor' },
  '47990': { area: 'Petaling Jaya', state: 'Selangor' },
  '48000': { area: 'Rawang', state: 'Selangor' },
  '48010': { area: 'Rawang', state: 'Selangor' },
  '48020': { area: 'Rawang', state: 'Selangor' },
  '48050': { area: 'Rawang', state: 'Selangor' },
  '48100': { area: 'Rawang', state: 'Selangor' },
  '48200': { area: 'Rawang', state: 'Selangor' },
  '48300': { area: 'Rawang', state: 'Selangor' },

  // Selangor — Gombak / Ampang / others
  '63000': { area: 'Cyberjaya', state: 'Selangor' },
  '63100': { area: 'Puchong', state: 'Selangor' },
  '63200': { area: 'Puchong', state: 'Selangor' },
  '63300': { area: 'Puchong', state: 'Selangor' },
  '63400': { area: 'Puchong', state: 'Selangor' },
  '63500': { area: 'Puchong', state: 'Selangor' },
  '63600': { area: 'Puchong', state: 'Selangor' },
  '63700': { area: 'Cyberjaya', state: 'Selangor' },
  '63710': { area: 'Cyberjaya', state: 'Selangor' },
  '63712': { area: 'Cyberjaya', state: 'Selangor' },
  '63714': { area: 'Cyberjaya', state: 'Selangor' },
  '63716': { area: 'Cyberjaya', state: 'Selangor' },
  '63718': { area: 'Cyberjaya', state: 'Selangor' },
  '63720': { area: 'Cyberjaya', state: 'Selangor' },
  '63722': { area: 'Cyberjaya', state: 'Selangor' },
  '63724': { area: 'Cyberjaya', state: 'Selangor' },
  '63726': { area: 'Cyberjaya', state: 'Selangor' },
  '63728': { area: 'Cyberjaya', state: 'Selangor' },
  '63730': { area: 'Cyberjaya', state: 'Selangor' },
  '63732': { area: 'Cyberjaya', state: 'Selangor' },
  '63734': { area: 'Cyberjaya', state: 'Selangor' },
  '63736': { area: 'Cyberjaya', state: 'Selangor' },
  '63738': { area: 'Cyberjaya', state: 'Selangor' },
  '63740': { area: 'Cyberjaya', state: 'Selangor' },
  '63742': { area: 'Cyberjaya', state: 'Selangor' },
  '63744': { area: 'Cyberjaya', state: 'Selangor' },
  '63746': { area: 'Cyberjaya', state: 'Selangor' },
  '63748': { area: 'Cyberjaya', state: 'Selangor' },
  '63750': { area: 'Cyberjaya', state: 'Selangor' },
  '63800': { area: 'Dengkil', state: 'Selangor' },
  '63900': { area: 'Sepang', state: 'Selangor' },
  '64000': { area: 'Ampang', state: 'Selangor' },
  '68000': { area: 'Ampang', state: 'Selangor' },
  '68100': { area: 'Ampang', state: 'Selangor' },

  // Negeri Sembilan
  '70000': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70100': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70200': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70300': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70400': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70450': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70500': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70600': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70700': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70800': { area: 'Seremban', state: 'Negeri Sembilan' },
  '70900': { area: 'Seremban', state: 'Negeri Sembilan' },
  '71000': { area: 'Port Dickson', state: 'Negeri Sembilan' },
  '71050': { area: 'Port Dickson', state: 'Negeri Sembilan' },
  '71100': { area: 'Port Dickson', state: 'Negeri Sembilan' },
  '71200': { area: 'Rembau', state: 'Negeri Sembilan' },
  '71300': { area: 'Rembau', state: 'Negeri Sembilan' },
  '71400': { area: 'Rembau', state: 'Negeri Sembilan' },
  '71450': { area: 'Rembau', state: 'Negeri Sembilan' },
  '71500': { area: 'Tampin', state: 'Negeri Sembilan' },
  '71600': { area: 'Tampin', state: 'Negeri Sembilan' },
  '71700': { area: 'Tampin', state: 'Negeri Sembilan' },
  '71800': { area: 'Tampin', state: 'Negeri Sembilan' },
  '71900': { area: 'Tampin', state: 'Negeri Sembilan' },
  '72000': { area: 'Kuala Pilah', state: 'Negeri Sembilan' },
  '72100': { area: 'Kuala Pilah', state: 'Negeri Sembilan' },
  '72200': { area: 'Kuala Pilah', state: 'Negeri Sembilan' },
  '72300': { area: 'Kuala Pilah', state: 'Negeri Sembilan' },
  '72400': { area: 'Kuala Pilah', state: 'Negeri Sembilan' },
  '73000': { area: 'Gemencheh', state: 'Negeri Sembilan' },
  '73100': { area: 'Gemencheh', state: 'Negeri Sembilan' },
  '73200': { area: 'Gemencheh', state: 'Negeri Sembilan' },
  '73300': { area: 'Gemencheh', state: 'Negeri Sembilan' },
  '73400': { area: 'Gemencheh', state: 'Negeri Sembilan' },
  '73500': { area: 'Gemas', state: 'Negeri Sembilan' },

  // Melaka
  '75000': { area: 'Melaka', state: 'Melaka' },
  '75050': { area: 'Melaka', state: 'Melaka' },
  '75100': { area: 'Melaka', state: 'Melaka' },
  '75150': { area: 'Melaka', state: 'Melaka' },
  '75200': { area: 'Melaka', state: 'Melaka' },
  '75250': { area: 'Melaka', state: 'Melaka' },
  '75300': { area: 'Melaka', state: 'Melaka' },
  '75350': { area: 'Melaka', state: 'Melaka' },
  '75400': { area: 'Melaka', state: 'Melaka' },
  '75450': { area: 'Melaka', state: 'Melaka' },
  '75460': { area: 'Melaka', state: 'Melaka' },
  '75500': { area: 'Melaka', state: 'Melaka' },
  '75550': { area: 'Melaka', state: 'Melaka' },
  '75600': { area: 'Ayer Keroh', state: 'Melaka' },
  '75700': { area: 'Ayer Keroh', state: 'Melaka' },
  '75710': { area: 'Ayer Keroh', state: 'Melaka' },
  '75720': { area: 'Ayer Keroh', state: 'Melaka' },
  '75730': { area: 'Ayer Keroh', state: 'Melaka' },
  '75740': { area: 'Ayer Keroh', state: 'Melaka' },
  '75750': { area: 'Ayer Keroh', state: 'Melaka' },
  '75760': { area: 'Ayer Keroh', state: 'Melaka' },
  '75770': { area: 'Ayer Keroh', state: 'Melaka' },
  '75780': { area: 'Ayer Keroh', state: 'Melaka' },
  '75790': { area: 'Ayer Keroh', state: 'Melaka' },
  '75800': { area: 'Ayer Keroh', state: 'Melaka' },
  '75900': { area: 'Masjid Tanah', state: 'Melaka' },
  '76000': { area: 'Alor Gajah', state: 'Melaka' },
  '76100': { area: 'Alor Gajah', state: 'Melaka' },
  '76200': { area: 'Alor Gajah', state: 'Melaka' },
  '76300': { area: 'Alor Gajah', state: 'Melaka' },
  '76400': { area: 'Alor Gajah', state: 'Melaka' },
  '77000': { area: 'Jasin', state: 'Melaka' },
  '77100': { area: 'Jasin', state: 'Melaka' },
  '77200': { area: 'Jasin', state: 'Melaka' },
  '77300': { area: 'Jasin', state: 'Melaka' },
  '77400': { area: 'Jasin', state: 'Melaka' },
  '77500': { area: 'Merlimau', state: 'Melaka' },
  '77600': { area: 'Merlimau', state: 'Melaka' },

  // Johor
  '79000': { area: 'Pontian', state: 'Johor' },
  '79100': { area: 'Pontian', state: 'Johor' },
  '79200': { area: 'Pontian', state: 'Johor' },
  '79300': { area: 'Pontian', state: 'Johor' },
  '79400': { area: 'Pontian', state: 'Johor' },
  '79500': { area: 'Pontian', state: 'Johor' },
  '79502': { area: 'Pontian', state: 'Johor' },
  '79503': { area: 'Pontian', state: 'Johor' },
  '79504': { area: 'Pontian', state: 'Johor' },
  '79506': { area: 'Pontian', state: 'Johor' },
  '79508': { area: 'Pontian', state: 'Johor' },
  '79510': { area: 'Pontian', state: 'Johor' },
  '79512': { area: 'Pontian', state: 'Johor' },
  '79514': { area: 'Pontian', state: 'Johor' },
  '79516': { area: 'Pontian', state: 'Johor' },
  '79518': { area: 'Pontian', state: 'Johor' },
  '79520': { area: 'Pontian', state: 'Johor' },
  '79522': { area: 'Pontian', state: 'Johor' },
  '79524': { area: 'Pontian', state: 'Johor' },
  '79526': { area: 'Pontian', state: 'Johor' },
  '79528': { area: 'Pontian', state: 'Johor' },
  '79530': { area: 'Pontian', state: 'Johor' },
  '79532': { area: 'Pontian', state: 'Johor' },
  '79534': { area: 'Pontian', state: 'Johor' },
  '79536': { area: 'Pontian', state: 'Johor' },
  '79538': { area: 'Pontian', state: 'Johor' },
  '79540': { area: 'Pontian', state: 'Johor' },
  '79542': { area: 'Pontian', state: 'Johor' },
  '79544': { area: 'Pontian', state: 'Johor' },
  '79546': { area: 'Pontian', state: 'Johor' },
  '79548': { area: 'Pontian', state: 'Johor' },
  '79550': { area: 'Pontian', state: 'Johor' },
  '79552': { area: 'Pontian', state: 'Johor' },
  '79554': { area: 'Pontian', state: 'Johor' },
  '79556': { area: 'Pontian', state: 'Johor' },
  '79558': { area: 'Pontian', state: 'Johor' },
  '79560': { area: 'Pontian', state: 'Johor' },
  '79562': { area: 'Pontian', state: 'Johor' },
  '79564': { area: 'Pontian', state: 'Johor' },
  '79566': { area: 'Pontian', state: 'Johor' },
  '79568': { area: 'Pontian', state: 'Johor' },
  '79570': { area: 'Pontian', state: 'Johor' },
  '79572': { area: 'Pontian', state: 'Johor' },
  '79574': { area: 'Pontian', state: 'Johor' },
  '79576': { area: 'Pontian', state: 'Johor' },
  '79578': { area: 'Pontian', state: 'Johor' },
  '79580': { area: 'Pontian', state: 'Johor' },
  '79582': { area: 'Pontian', state: 'Johor' },
  '79584': { area: 'Pontian', state: 'Johor' },
  '79586': { area: 'Pontian', state: 'Johor' },
  '79588': { area: 'Pontian', state: 'Johor' },
  '79590': { area: 'Pontian', state: 'Johor' },
  '79592': { area: 'Pontian', state: 'Johor' },
  '79594': { area: 'Pontian', state: 'Johor' },
  '79596': { area: 'Pontian', state: 'Johor' },
  '79598': { area: 'Pontian', state: 'Johor' },
  '79600': { area: 'Pontian', state: 'Johor' },
  '80000': { area: 'Johor Bahru', state: 'Johor' },
  '80100': { area: 'Johor Bahru', state: 'Johor' },
  '80150': { area: 'Johor Bahru', state: 'Johor' },
  '80200': { area: 'Johor Bahru', state: 'Johor' },
  '80250': { area: 'Johor Bahru', state: 'Johor' },
  '80300': { area: 'Johor Bahru', state: 'Johor' },
  '80350': { area: 'Johor Bahru', state: 'Johor' },
  '80400': { area: 'Johor Bahru', state: 'Johor' },
  '80500': { area: 'Johor Bahru', state: 'Johor' },
  '80600': { area: 'Johor Bahru', state: 'Johor' },
  '80700': { area: 'Johor Bahru', state: 'Johor' },
  '80800': { area: 'Johor Bahru', state: 'Johor' },
  '80900': { area: 'Johor Bahru', state: 'Johor' },
  '81000': { area: 'Kulai', state: 'Johor' },
  '81100': { area: 'Johor Bahru', state: 'Johor' },
  '81200': { area: 'Johor Bahru', state: 'Johor' },
  '81300': { area: 'Skudai', state: 'Johor' },
  '81400': { area: 'Senai', state: 'Johor' },
  '81500': { area: 'Johor Bahru', state: 'Johor' },
  '81600': { area: 'Pulai', state: 'Johor' },
  '81700': { area: 'Johor Bahru', state: 'Johor' },
  '81800': { area: 'Ulu Tiram', state: 'Johor' },
  '81900': { area: 'Kota Tinggi', state: 'Johor' },
  '82000': { area: 'Pontian', state: 'Johor' },
  '82100': { area: 'Pontian', state: 'Johor' },
  '82200': { area: 'Pontian', state: 'Johor' },
  '82300': { area: 'Batu Pahat', state: 'Johor' },
  '83000': { area: 'Batu Pahat', state: 'Johor' },
  '83100': { area: 'Batu Pahat', state: 'Johor' },
  '83200': { area: 'Batu Pahat', state: 'Johor' },
  '83300': { area: 'Batu Pahat', state: 'Johor' },
  '83400': { area: 'Batu Pahat', state: 'Johor' },
  '83500': { area: 'Batu Pahat', state: 'Johor' },
  '83600': { area: 'Batu Pahat', state: 'Johor' },
  '83700': { area: 'Batu Pahat', state: 'Johor' },
  '83800': { area: 'Batu Pahat', state: 'Johor' },
  '83900': { area: 'Batu Pahat', state: 'Johor' },
  '84000': { area: 'Muar', state: 'Johor' },
  '84100': { area: 'Muar', state: 'Johor' },
  '84200': { area: 'Muar', state: 'Johor' },
  '84300': { area: 'Muar', state: 'Johor' },
  '84400': { area: 'Muar', state: 'Johor' },
  '84500': { area: 'Muar', state: 'Johor' },
  '84600': { area: 'Muar', state: 'Johor' },
  '84700': { area: 'Muar', state: 'Johor' },
  '84800': { area: 'Muar', state: 'Johor' },
  '84900': { area: 'Muar', state: 'Johor' },
  '85000': { area: 'Segamat', state: 'Johor' },
  '85100': { area: 'Segamat', state: 'Johor' },
  '85200': { area: 'Segamat', state: 'Johor' },
  '85300': { area: 'Segamat', state: 'Johor' },
  '85400': { area: 'Segamat', state: 'Johor' },
  '85500': { area: 'Segamat', state: 'Johor' },
  '85600': { area: 'Segamat', state: 'Johor' },
  '85700': { area: 'Segamat', state: 'Johor' },
  '85800': { area: 'Segamat', state: 'Johor' },
  '85900': { area: 'Segamat', state: 'Johor' },
  '86000': { area: 'Kluang', state: 'Johor' },
  '86100': { area: 'Kluang', state: 'Johor' },
  '86200': { area: 'Kluang', state: 'Johor' },
  '86300': { area: 'Kluang', state: 'Johor' },
  '86400': { area: 'Kluang', state: 'Johor' },
  '86500': { area: 'Kluang', state: 'Johor' },
  '86600': { area: 'Kluang', state: 'Johor' },
  '86700': { area: 'Kluang', state: 'Johor' },
  '86800': { area: 'Kluang', state: 'Johor' },
  '86900': { area: 'Kluang', state: 'Johor' },
};

// ---------------------------------------------------------------------------
// Prefix ranges — fallback when exact postcode not in map
// Each entry: [minPrefix, maxPrefix, areaInfo]
// ---------------------------------------------------------------------------
const RANGES: [number, number, AreaInfo][] = [
  [1, 2, { area: 'Kangar', state: 'Perlis' }],
  [5, 9, { area: 'Alor Setar / Kedah', state: 'Kedah' }],
  [10, 14, { area: 'Georgetown / Penang', state: 'Penang' }],
  [15, 18, { area: 'Kota Bharu', state: 'Kelantan' }],
  [20, 24, { area: 'Kuala Terengganu', state: 'Terengganu' }],
  [25, 28, { area: 'Kuantan / Pahang', state: 'Pahang' }],
  [30, 36, { area: 'Ipoh / Perak', state: 'Perak' }],
  [40, 48, { area: 'Selangor', state: 'Selangor' }],
  [50, 60, { area: 'Kuala Lumpur', state: 'Kuala Lumpur' }],
  [61, 61, { area: 'Kuala Lumpur', state: 'Kuala Lumpur' }],
  [62, 62, { area: 'Putrajaya', state: 'Putrajaya' }],
  [63, 68, { area: 'Selangor', state: 'Selangor' }],
  [69, 69, { area: 'Pahang', state: 'Pahang' }],
  [70, 73, { area: 'Seremban / Negeri Sembilan', state: 'Negeri Sembilan' }],
  [75, 78, { area: 'Melaka', state: 'Melaka' }],
  [79, 86, { area: 'Johor', state: 'Johor' }],
  [87, 91, { area: 'Kota Kinabalu / Sabah', state: 'Sabah' }],
  [93, 98, { area: 'Kuching / Sarawak', state: 'Sarawak' }],
];

// ---------------------------------------------------------------------------
// Keyword fallback — scans address text when no postcode found
// ---------------------------------------------------------------------------
const KEYWORDS: [RegExp, AreaInfo][] = [
  // KL areas
  [/\bklcc\b|\btwin tower/i, { area: 'KLCC', state: 'Kuala Lumpur' }],
  [/\bbukit bintang\b|\bbb park\b/i, { area: 'Bukit Bintang', state: 'Kuala Lumpur' }],
  [/\bbangsar\b/i, { area: 'Bangsar', state: 'Kuala Lumpur' }],
  [/\bmont.?kiara\b|\bmontkiara\b/i, { area: 'Mont Kiara', state: 'Kuala Lumpur' }],
  [/\bdamansara heights\b|\buph\b/i, { area: 'Damansara Heights', state: 'Kuala Lumpur' }],
  [/\bcheras\b/i, { area: 'Cheras', state: 'Kuala Lumpur' }],
  [/\bsetapak\b/i, { area: 'Setapak', state: 'Kuala Lumpur' }],
  [/\bkepong\b/i, { area: 'Kepong', state: 'Kuala Lumpur' }],
  [/\bsentul\b/i, { area: 'Sentul', state: 'Kuala Lumpur' }],
  [/\bbatu caves\b|\bgombak\b/i, { area: 'Batu Caves / Gombak', state: 'Selangor' }],
  [/\bbukit jalil\b/i, { area: 'Bukit Jalil', state: 'Kuala Lumpur' }],
  [/\bsr[i]? petaling\b|\bsri petaling\b/i, { area: 'Sri Petaling', state: 'Kuala Lumpur' }],
  [/\bsalak selatan\b|\bsalak south\b/i, { area: 'Salak South', state: 'Kuala Lumpur' }],
  [/\bbrickfields\b|\bkl sentral\b|\bkl central\b/i, { area: 'Brickfields', state: 'Kuala Lumpur' }],
  [/\bmasjid india\b|\bchow kit\b/i, { area: 'Chow Kit', state: 'Kuala Lumpur' }],
  [/\bwangsa maju\b/i, { area: 'Wangsa Maju', state: 'Kuala Lumpur' }],
  [/\bkeramat\b|\bpandan\b/i, { area: 'Keramat / Pandan', state: 'Kuala Lumpur' }],
  [/\btitiwangsa\b/i, { area: 'Titiwangsa', state: 'Kuala Lumpur' }],
  [/\bseputeh\b/i, { area: 'Seputeh', state: 'Kuala Lumpur' }],
  [/\bjalan ipoh\b/i, { area: 'Jalan Ipoh', state: 'Kuala Lumpur' }],
  [/\bpudu\b/i, { area: 'Pudu', state: 'Kuala Lumpur' }],
  [/\bimbi\b/i, { area: 'Imbi', state: 'Kuala Lumpur' }],

  // Selangor areas
  [/\bpetaling jaya\b|\b\bpj\b/i, { area: 'Petaling Jaya', state: 'Selangor' }],
  [/\bsubang jaya\b|\bsubang\b/i, { area: 'Subang Jaya', state: 'Selangor' }],
  [/\bshah alam\b/i, { area: 'Shah Alam', state: 'Selangor' }],
  [/\bklang\b|\bport klang\b/i, { area: 'Klang', state: 'Selangor' }],
  [/\bampang\b/i, { area: 'Ampang', state: 'Selangor' }],
  [/\bpuchong\b/i, { area: 'Puchong', state: 'Selangor' }],
  [/\bkajang\b/i, { area: 'Kajang', state: 'Selangor' }],
  [/\bserdang\b/i, { area: 'Serdang', state: 'Selangor' }],
  [/\bsepang\b/i, { area: 'Sepang', state: 'Selangor' }],
  [/\bcyberjaya\b/i, { area: 'Cyberjaya', state: 'Selangor' }],
  [/\brawang\b/i, { area: 'Rawang', state: 'Selangor' }],
  [/\bdamansara\b/i, { area: 'Damansara', state: 'Selangor' }],
  [/\bbangi\b|\bbandar baru bangi\b/i, { area: 'Bangi', state: 'Selangor' }],
  [/\bsemenyih\b/i, { area: 'Semenyih', state: 'Selangor' }],
  [/\bbalakong\b/i, { area: 'Balakong', state: 'Selangor' }],
  [/\bsunway\b/i, { area: 'Sunway', state: 'Selangor' }],
  [/\bkota damansara\b/i, { area: 'Kota Damansara', state: 'Selangor' }],
  [/\bss2\b|\bss3\b|\bss4\b|\bss5\b|\bss6\b|\bss7\b|\bss1[0-9]\b/i, { area: 'Petaling Jaya', state: 'Selangor' }],
  [/\busj\b|\bu\s*s\s*j\b/i, { area: 'Subang Jaya', state: 'Selangor' }],

  // Putrajaya
  [/\bputrajaya\b/i, { area: 'Putrajaya', state: 'Putrajaya' }],

  // Other states — broad match
  [/\bgeorgetown\b|\bpenang\b|\bpulau pinang\b/i, { area: 'Penang', state: 'Penang' }],
  [/\bipoh\b|\bperak\b/i, { area: 'Ipoh', state: 'Perak' }],
  [/\bjohor bahru\b|\bjb\b|\bjohor\b/i, { area: 'Johor Bahru', state: 'Johor' }],
  [/\bseremban\b|\bnegeri sembilan\b|\bns\b/i, { area: 'Seremban', state: 'Negeri Sembilan' }],
  [/\bmelaka\b|\bmalacca\b/i, { area: 'Melaka', state: 'Melaka' }],
  [/\bkuantan\b|\bpahang\b/i, { area: 'Kuantan', state: 'Pahang' }],
  [/\bkota bharu\b|\bkelantan\b/i, { area: 'Kota Bharu', state: 'Kelantan' }],
  [/\bkuala terengganu\b|\bterengganu\b/i, { area: 'Kuala Terengganu', state: 'Terengganu' }],
  [/\balor setar\b|\bkedah\b/i, { area: 'Alor Setar', state: 'Kedah' }],
  [/\bkangar\b|\bperlis\b/i, { area: 'Kangar', state: 'Perlis' }],
  [/\bkota kinabalu\b|\bkk\b|\bsabah\b/i, { area: 'Kota Kinabalu', state: 'Sabah' }],
  [/\bkuching\b|\bsarawak\b/i, { area: 'Kuching', state: 'Sarawak' }],
  [/\blabuan\b/i, { area: 'Labuan', state: 'Labuan' }],
];

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Extract the first 5-digit postcode from an address string. */
function extractPostcode(address: string): string | null {
  const m = address.match(/\b(\d{5})\b/);
  return m ? m[1] : null;
}

/**
 * Resolve area and state from a free-text Malaysian address.
 * Returns null when no match is found.
 */
export function resolveAreaFromAddress(address: string | undefined | null): AreaInfo | null {
  if (!address?.trim()) return null;

  // 1. Exact postcode match
  const postcode = extractPostcode(address);
  if (postcode) {
    const exact = EXACT[postcode];
    if (exact) return exact;

    // 2. Range fallback using first two digits
    const prefix = parseInt(postcode.slice(0, 2), 10);
    for (const [min, max, info] of RANGES) {
      if (prefix >= min && prefix <= max) return info;
    }
  }

  // 3. Keyword scan
  for (const [pattern, info] of KEYWORDS) {
    if (pattern.test(address)) return info;
  }

  return null;
}

// ---------------------------------------------------------------------------
// Seed export — converts static tables into PostcodeEntry-shaped objects
// for PostcodeService.seed()
// ---------------------------------------------------------------------------
export interface SeedEntry {
  id: string;
  postcode?: string;
  minPrefix?: number;
  maxPrefix?: number;
  pattern?: string;
  area: string;
  state: string;
  type: 'exact' | 'range' | 'keyword';
}

export function getSeedEntries(): SeedEntry[] {
  const entries: SeedEntry[] = [];

  Object.entries(EXACT).forEach(([postcode, info]) => {
    entries.push({ id: postcode, postcode, area: info.area, state: info.state, type: 'exact' });
  });

  RANGES.forEach(([min, max, info]) => {
    entries.push({ id: `range_${min}_${max}`, minPrefix: min, maxPrefix: max, area: info.area, state: info.state, type: 'range' });
  });

  KEYWORDS.forEach(([pattern, info], i) => {
    entries.push({ id: `kw_${i}`, pattern: pattern.source, area: info.area, state: info.state, type: 'keyword' });
  });

  return entries;
}
